str = ''
str += '<div class="footer">'
str += '	<div class="f_wrap">'
str += '		<div class="f_logo"><img src="img/common/f_logo.png"></div>'
str += '		<div class="info">'
str += '			<ul class="terms">'
str += '				<li><a href="privacy.html">개인정보처리방침</a></li>'
str += '			</ul>'
str += '			<ul class="add">'
str += '				<li>만세보령농업회사법인 주식회사<span class="bar"></span></li>'
str += '				<li>충청남도 보령시 대해로 415<span class="bar"></span></li>'
str += '				<li>T. 041-933-9201</li>'
str += '			</ul>'
str += '			<p>COPYRIGHT ⓒ Boreong Localfood. All Right Reserved.</p>'
str += '		</div>'
str += '	</div>'
str += '</div>'

document.write( str );