str = ''
str += '<div id="header">'
str += '	<div class="h_group">'
str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html"><img src="img/common/logo.png" alt="만세보령농식품직판장" /></a>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<button class="btn_menu" type="button">전체메뉴 열기</button>'
str += '				<div class="box">'
str += '					<button class="btn_close" type="button">전체메뉴 닫기</button>'
str += '					<ul>'
str += '						<li><a href="javascript:">만세보령농식품직판장</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="greeting.html">인사말</a></li>'
str += '									<li><a href="intro.html">농식품 직판장 소개</a></li>'
str += '									<li><a href="contact.html">오시는 길</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="javascript:">특산품 안내</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="majorbiz.html">주요사업</a></li>'
str += '									<li><a href="product.html">제품소개</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="javascript:">알림마당</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="news_list.html">농가소식</a></li>'
str += '									<li><a href="notice_list.html">공지사항</a></li>'
str += '									<li><a href="guide.html">시설안내</a></li>'
str += '									<li><a href="photo_list.html">포토 갤러리</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="javascript:">열린마당</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="tour.html">주변 관광지</a></li>'
str += '									<li><a href="faq.html">자주하는 질문</a></li>'
str += '									<li><a href="inquery.html">1:1 문의하기</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += '			<div class="search_area">'
str += '				<div class="sizing_wrap">'
str += '					<form method="post" name="" action="">'
str += '						<fieldset>'
str += '							<legend>검색</legend>'
str += '							<input type="text" name="" id="inp_search" placeholder="검색어를 입력하세요">'
str += '							<a href="javascript:" class="btn_search"><span class="ico ico_search">검색</span></a>'
str += '							<a href="javascript:" class="btn_cl"><span class="ico ico_cl">검색 닫기</span></a>'
str += '						</fieldset>'
str += '					</form>'
str += '				</div>'
str += '			</div>'
str += '		</div>'
str += ''
str += '		<i class="bgDepth"></i>'
str += ''
str += '	</div>'
str += '</div>'

document.write(str);